logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  h2:
    console:
      enabled: true